import Sidebar from "@/components/SideBar"

export const metadata = {
    title: 'Next js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>

                <div style={{ display: 'flex', gap: '30px' }}>

                    <Sidebar />

                    {children}

                </div>

            </body>
        </html>
    )
}